blank_issues_enabled: false
contact_links:
  - name: Global ESLint Config Docs
    url: https://eslint.org/docs/latest/use/configure/configuration-files
    about: Official ESLint configuration documentation
  - name: GitHub Discussions
    url: https://github.com/santi020k/eslint-config/discussions
    about: Ask questions and discuss ideas
